package com.arkhamusserver.arkhamus.view.levelDesign

data class LevelFromJson(
    var levelId: Long? = null,
    var levelVersion: Long? = null,
    var levelHeight: Long? = null,
    var levelWidth: Long? = null,
    var questGivers: List<QuestGiverFromJson> = emptyList(),
    var levelTasks: List<LevelTaskFromJson> = emptyList(),
    var containers: List<ContainerFromJson> = emptyList(),
    var lanterns: List<LanternFromJson> = emptyList(),
    var altars: List<AltarFromJson> = emptyList(),
    var ritualZones: List<RitualAreaFromJson> = emptyList(),
    var startMarkers: List<StartMarkerFromJson> = emptyList(),
    var crafters: List<CrafterFromJson> = emptyList(),
    var clueZones: List<ZoneFromJson> = emptyList(),
    var soundClueZones: List<ZoneFromJson> = emptyList(),
    var auraClueZones: List<ZoneFromJson> = emptyList(),
    var banZones: List<ZoneFromJson> = emptyList(),
    var doors: List<DoorFromJson> = emptyList(),
    var ritualThresholds: List<ThresholdFromJson> = emptyList(),
    var banThresholds: List<ThresholdFromJson> = emptyList(),
    var votespots: List<VoteSpotFromJson> = emptyList(),
    var inscriptionClues: List<InscriptionClueFromJson> = emptyList(),
    var inscriptionGlyphs: List<InscriptionGlyphFromJson> = emptyList(),
    var scentClues: List<ScentClueFromJson> = emptyList(),
    var soundClues: List<JsonSoundClue>,
    var auraClues: List<JsonAuraClue>,
    var corruptionClues: List<JsonCorruptionClue>,
    var distortionClues: List<JsonDistortionClue>,
    var soundClueJammers: List<JsonSoundClueJammer>,
    var visibilityDoors: List<VisibilityDoorFromJson>,
    var visibilityWalls: List<List<PointJson>>
)