package com.arkhamusserver.arkhamus.model.enums.ingame

import com.arkhamusserver.arkhamus.model.enums.ingame.RoleTypeInGame.CULTIST
import com.arkhamusserver.arkhamus.model.enums.ingame.RoleTypeInGame.INVESTIGATOR

enum class ClassInGame(val id: Int, val roleType: RoleTypeInGame) {
    MIND_HEALER(101, INVESTIGATOR),
    BREADWINNER(102, INVESTIGATOR),

    AAMON_CULTIST(201, CULTIST),
    BELETH_CULTIST(202, CULTIST),
    BHOLES_CULTIST(203, CULTIST),
    COLOUR_OUT_OF_SPACE_CULTIST(204, CULTIST),
    CTHULHU_CULTIST(205, CULTIST),
    CYBELE_CULTIST(206, CULTIST),
    CZEOTHOQUA_CULTIST(207, CULTIST),
    DAGON_CULTIST(208, CULTIST),
    GREEN_FLAME_CULTIST(209, CULTIST),
    KING_IN_YELLOW_CULTIST(210, CULTIST),
    MI_GO_CULTIST(211, CULTIST),
    NAMELESS_WINDS_CULTIST(212, CULTIST),
    NINGISHZIDA_CULTIST(213, CULTIST),
    NYARLATHOTEP_CULTIST(214, CULTIST),
    PNAKOTIC_HORRORS_CULTIST(215, CULTIST),
    RED_MASK_CULTIST(216, CULTIST),
    SHUB_NIGGURATH_CULTIST(217, CULTIST),
    TZONTEMOC_CULTIST(218, CULTIST),
    YERLEG_CULTIST(219, CULTIST),
    YOG_SOTHOTH_CULTIST(220, CULTIST),
}