package com.arkhamusserver.arkhamus.model.enums.ingame

import com.arkhamusserver.arkhamus.model.enums.ingame.ItemType.*

enum class Item(
    private val id: Long,
    private val itemType: ItemType,
) {
    //LOOT 1**
    I1(101, LOOT),
    I2(102, LOOT),
    I3(103, LOOT),
    I4(104, LOOT),
    I5(105, LOOT),

    //RARE_LOOT 2*
    BLACK_STONE(201, RARE_LOOT),
    BOOK(202, RARE_LOOT),
    CLOCK(203, RARE_LOOT),
    EYE(204, RARE_LOOT),
    MASK(205, RARE_LOOT),
    PLATE(206, RARE_LOOT),
    RING(207, RARE_LOOT),
    SCYTHE(208, RARE_LOOT),
    TEAR(209, RARE_LOOT),

    //CULTIST_LOOT 3**
    SOUL_STONE(301, CULTIST_LOOT),

    //CRAFT_T2 4**
    VIOLET_SCROLL(401, CRAFT_T2),

    //INVESTIGATION 5**
    INSCRIPTION_INVESTIGATION_ITEM(501, INVESTIGATION),
    SOUND_INVESTIGATION_ITEM(502, INVESTIGATION),
    SCENT_INVESTIGATION_ITEM(503, INVESTIGATION),
    AURA_INVESTIGATION_ITEM(504, INVESTIGATION),
    CORRUPTION_INVESTIGATION_ITEM(505, INVESTIGATION),
    OMEN_INVESTIGATION_ITEM(506, INVESTIGATION),
    DISTORTION_INVESTIGATION_ITEM(507, INVESTIGATION),

    //USEFUL_ITEM 6**
    VEIL(601, USEFUL_ITEM),

    //CULTIST_ITEM 7**
    MOON_STONE(701, CULTIST_ITEM),

    //CORK 8**
    CORK_AAMON(801, CORK),
    CORK_BELETH(802, CORK),
    CORK_BHOLES(803, CORK),
    CORK_COLOUR_OUT_OF_SPACE(804, CORK),
    CORK_CTHULHU(805, CORK),
    CORK_CYBELE(806, CORK),
    CORK_CZEOTHOQUA(807, CORK),
    CORK_DAGON(808, CORK),
    CORK_GREEN_FLAME(809, CORK),
    CORK_KING_IN_YELLOW(810, CORK),
    CORK_MI_GO(811, CORK),
    CORK_NAMELESS_WINDS(812, CORK),
    CORK_NINGISHZIDA(813, CORK),
    CORK_NYARLATHOTEP(814, CORK),
    CORK_PNAKOTIC_HORRORS(815, CORK),
    CORK_RED_MASK(816, CORK),
    CORK_SHUB_NIGGURATH(817, CORK),
    CORK_TZONTEMOC(818, CORK),
    CORK_YERLEG(819, CORK),
    CORK_YOG_SOTHOTH(820, CORK),

    //ADVANCED_USEFUL_ITEM 9**
    CLOAK_OF_FLAMES(901, ADVANCED_USEFUL_ITEM),

    //ADVANCED_CULTIST_ITEM 10**
    BONE_CHIMES(1001, ADVANCED_CULTIST_ITEM)
    ;

    fun getItemType(): ItemType =
        itemType

    fun getId(): Long =
        id
}