package com.arkhamusserver.arkhamus.model.enums.ingame.core

import com.arkhamusserver.arkhamus.model.enums.ingame.core.ItemType.*

enum class Item(
    val id: Int,
    val itemType: ItemType,
) {
    PURE_NOTHING(-1, TECH_TYPE),

    //LOOT 1**
    SAINT_QUARTZ(101, LOOT),
    CRYSTALLIZED_BLOOD(102, LOOT),
    ELDER_SIGN(103, LOOT),
    CORRUPTED_TOPAZ(104, LOOT),
    HIGGS_BOSON(105, LOOT),
    RAGS(106, LOOT),
    BLIGHTING_JEWEL(107, LOOT),

    //RARE_LOOT 2*
    BLACK_STONE(201, RARE_LOOT),
    BOOK(202, RARE_LOOT),
    CLOCK(203, RARE_LOOT),
    EYE(204, RARE_LOOT),
    MASK(205, RARE_LOOT),
    PLATE(206, RARE_LOOT),
    RING(207, RARE_LOOT),
    SCYTHE(208, RARE_LOOT),
    TEAR(209, RARE_LOOT),

    //CULTIST_LOOT 3**
    SOUL_STONE(301, CULTIST_LOOT),
    DARK_ESSENCE(302, CULTIST_LOOT),
    STRANGE_BONE(303, CULTIST_LOOT),

    //CRAFT_T2 4**
    VIOLET_SCROLL(401, CRAFT_T2),
    GREEN_SCROLL(402, CRAFT_T2),
    BLUE_EGG(403, CRAFT_T2),
    ORANGE_EGG(404, CRAFT_T2),
    GREEN_EGG(405, CRAFT_T2),

    //INVESTIGATION 5**
    INSCRIPTION_INVESTIGATION_ITEM(501, INVESTIGATION),
    SOUND_INVESTIGATION_ITEM(502, INVESTIGATION),
    SCENT_INVESTIGATION_ITEM(503, INVESTIGATION),
    AURA_INVESTIGATION_ITEM(504, INVESTIGATION),
    CORRUPTION_INVESTIGATION_ITEM(505, INVESTIGATION),
    OMEN_INVESTIGATION_ITEM(506, INVESTIGATION),
    DISTORTION_INVESTIGATION_ITEM(507, INVESTIGATION),

    //USEFUL_ITEM 6**
    VEIL(601, USEFUL_ITEM),
    TOWN_PORTAL_SCROLL(602, USEFUL_ITEM),
    VOTE_TOKEN(603, USEFUL_ITEM),
    SCIENTIFIC_GIZMO(604, USEFUL_ITEM),

    //CULTIST_ITEM 7**
    MOON_STONE(701, CULTIST_ITEM),
    CURSED_POTATO(702, CULTIST_ITEM),
    RITUAL_DAGGER(703, CULTIST_ITEM),

    //CORK 8**
    CORK_AAMON(801, CORK),
    CORK_BELETH(802, CORK),
    CORK_BHOLES(803, CORK),
    CORK_COLOUR_OUT_OF_SPACE(804, CORK),
    CORK_CTHULHU(805, CORK),
    CORK_CYBELE(806, CORK),
    CORK_CZEOTHOQUA(807, CORK),
    CORK_DAGON(808, CORK),
    CORK_GREEN_FLAME(809, CORK),
    CORK_KING_IN_YELLOW(810, CORK),
    CORK_MI_GO(811, CORK),
    CORK_NAMELESS_WINDS(812, CORK),
    CORK_NINGISHZIDA(813, CORK),
    CORK_NYARLATHOTEP(814, CORK),
    CORK_PNAKOTIC_HORRORS(815, CORK),
    CORK_RED_MASK(816, CORK),
    CORK_SHUB_NIGGURATH(817, CORK),
    CORK_TZONTEMOC(818, CORK),
    CORK_YERLEG(819, CORK),
    CORK_YOG_SOTHOTH(820, CORK),

    //ADVANCED_USEFUL_ITEM 9**
    CLOAK_OF_FLAMES(901, ADVANCED_USEFUL_ITEM),
    INVULNERABILITY_POTION(902, ADVANCED_USEFUL_ITEM),
    TOWN_PORTAL_AMULET(903, ADVANCED_USEFUL_ITEM),

    //ADVANCED_CULTIST_ITEM 10**
    BONE_CHIMES(1001, ADVANCED_CULTIST_ITEM),
    PIPE_OF_INSIGHT(1002, ADVANCED_CULTIST_ITEM),
    CIRCLET_OF_NOBILITY(1003, ADVANCED_CULTIST_ITEM),
    ;

}