package com.arkhamusserver.arkhamus.view.dto.steam

data class SteamAuthRequestDto(
    val clientSteamID: String,        // Client's Steam ID
    val authTicket: String            // Auth Ticket generated by Steam API
)